#version: '3.8'

services:
  # PHP服务
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./project:/var/www/html
    depends_on:
      - mysql_master
      - redis_master
      - rabbitmq
    networks:
      - api_server_network

  # Nginx服务
  nginx:
    image: nginx:1.26
    container_name: laravel_nginx
    ports:
      - "81:80"
    volumes:
      - ./project:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - api_server_network

  # MySQL主服务器
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./docker/mysql/master:/etc/mysql/conf.d
    networks:
      - api_server_network

  # MySQL从服务器
  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_slave_data:/var/lib/mysql
      - ./docker/mysql/slave:/etc/mysql/conf.d
    depends_on:
      - mysql_master
    networks:
      - api_server_network

  # Redis主服务器
  redis_master:
    # image: redis:alpine
    image: redis:7.4.2-bookworm
    container_name: redis_master
    ports:
      - "6380:6379"
    volumes:
      - ./docker/redis/master:/usr/local/etc/redis
    networks:
      - api_server_network

  # Redis从服务器
  redis_slave:
    image: redis:7.4.2-bookworm
    container_name: redis_slave
    ports:
      - "6381:6379"
    volumes:
      - ./docker/redis/slave:/usr/local/etc/redis
    depends_on:
      - redis_master
    networks:
      - api_server_network

  # RabbitMQ服务
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - api_server_network

  # Elasticsearch服务
  elasticsearch:
    image: elastic/elasticsearch:7.17.28
    container_name: elasticsearch
    restart: no
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DntKdS*4SG9ZMDFOBsh2
      - KIBANA_SYSTEM_USERNAME=kibana_system
      - KIBANA_SYSTEM_PASSWORD=kibana123
      # logstash_system: Logstash 系统用户
      - LOGSTASH_SYSTEM_USERNAME=logstash_system
      - LOGSTASH_SYSTEM_PASSWORD=logstash123
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  # 设置 JVM 堆大小

    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./docker/elasticsearch/logs:/usr/share/elasticsearch/logs
      # 挂载日志目录
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      # 挂载数据目录
      - ./docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      # 挂载插件目录
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # 挂载配置文件
      - ./docker/elasticsearch/certs:/usr/share/elasticsearch/config/certs
      # 挂载证书目录
    networks:
      - api_server_network


  # Logstash服务
  logstash:
    image: elastic/logstash:7.17.28
    container_name: logstash
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DntKdS*4SG9ZMDFOBsh2
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - api_server_network
  # Kibana服务
  kibana:
    image: elastic/kibana:7.17.28
    restart: no # 不重启  
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      # - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT} KIBANA_SYSTEM_PASSWORD
      - ELASTICSEARCH_HOSTS=http//elasticsearch:9200
      - KIBANA_SYSTEM_USERNAME=kibana_system
      - KIBANA_SYSTEM_PASSWORD=kibana123
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    volumes:
      - ./docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - api_server_network

  # Consul服务注册中心
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - api_server_network

networks:
  api_server_network:
    external: true
    driver: bridge

volumes:
  mysql_master_data:
  mysql_slave_data:
  elasticsearch_data: